DistinctHottubRepairandService/urls.py
from django.urls import path, include

app_name = 'distinct_hottub'

urlpatterns = [
    path('', include('users.urls')),
    path('customers/', include('customers.urls')),
    path('service/', include('service.urls')),
]

customers/urls.py
from django.urls import path
from . import views

app_name = 'customers'

urlpatterns = [
    path('', views.CustomerList.as_view(), name='customer_list'),
    path('new/', views.CustomerCreate.as_view(), name='customer_new'),
    path('<int:pk>/detail/', views.CustomerDetail.as_view(), name='customer_detail'),
    path('<int:pk>/update/', views.CustomerUpdate.as_view(), name='customer_update'),
    path('<int:pk>/spa/', views.create_spa, name='spa_new'),
    path('<int:id>/spa/<int:pk>/update/', views.UpdateSpa.as_view(), name='spa_update'),
    path('<int:id>/spa/<int:pk>/detail/', views.SpaDetail.as_view(), name='spa_detail'),
]

service/urls.py
from django.urls import path
from . import views

app_name = 'service'

urlpatterns = [
    path('', views.ServiceTicketList.as_view(), name='ticket_list'),
    # path('new/', views.ServiceTicketScratch.as_view(), name='ticket_new'),
    path('<int:id>/new/', views.create_service_ticket, name='ticket_new'),
    path('<int:id>/update/<int:pk>/', views.update_service_ticket, name='ticket_update'),
    path('<int:id>/detail/<int:pk>/', views.ServiceTicketDetail.as_view(), name='ticket_detail'),
    path('schedule/', views.schedule_list, name='schedule_list'),
    path('parts/', views.PartListView.as_view(), name='part_list'),
    path('parts/<int:pk>/detail/', views.PartDetail.as_view(), name='part_detail'),
    path('parts', views.PartUpdate.as_view(), name='part_update'),
    path('parts/new/', views.PartNew.as_view(), name='part_new'),
    # path('invoice/', views.InvoiceList.as_view(), name='invoice_list'),
    path('invoice/<str:closed>/', views.InvoiceList.as_view(), name='invoice_list'),
    path('invoice/new/', views.InvoiceNew.as_view(), name='invoice_new'),
    path('invoive/<int:pk>/detail/', views.InvoiceDetail.as_view(), name='invoice_detail'),
    path('invoice/<int:pk>/update/', views.InvoiceUpdate.as_view(), name='invoice_update'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.login_view, name='user_login'),
    path('logout/', views.logout_view, name='user_logout'),
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('new/', views.UserCreate.as_view(), name='user_new'),
    path('<int:pk>/detail/', views.UserDetail.as_view(), name='user_detail'),
    path('<int:pk>/update/', views.UserUpdate.as_view(), name='user_update'),
]

service/models.py
from django.db import models
from django.shortcuts import reverse


class ServiceTicket(models.Model):
    customer = models.ForeignKey('customers.Customer', related_name='+', on_delete=models.DO_NOTHING)
    spa = models.ForeignKey('customers.CustomerSpa', related_name='+', on_delete=models.DO_NOTHING)
    technician = models.ForeignKey('users.InternalUser', related_name='+', on_delete=models.DO_NOTHING)
    service_date = models.DateField(default=None, blank=True)
    primary_issue = models.TextField(default=None)
    date_entered = models.DateTimeField(auto_now_add=True)
    num_visits = models.IntegerField(default=1)
    is_complete = models.BooleanField(default=False)
    date_completed = models.DateField(default=None, blank=True, null=True)
    under_warranty = models.BooleanField(default=False)
    upfront_charges = models.FloatField(default=0.00)

    def __str__(self):
        return f'{self.customer}/{self.spa}/{self.technician}'

    def get_absolute_url(self):
        return reverse('customers:customer_detail', kwargs={'id': self.customer_id})


class PartsList(models.Model):
    part_name = models.CharField(max_length=200, default=None)
    part_number = models.CharField(max_length=100, default=None)
    part_description = models.TextField(default=None)
    part_cost = models.FloatField(default=0.00)
    part_price = models.FloatField(default=0.00)
    is_discontinued = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.part_name}/{self.part_number}'

    def get_absolute_url(self):
        return reverse('service:part_list')


class Invoice(models.Model):
    service_ticket = models.ForeignKey(ServiceTicket, related_name='+', on_delete=models.DO_NOTHING)
    subtotal = models.FloatField(default=0.00)
    tax = models.FloatField(default=0.00)
    total = models.FloatField(default=0.00)
    is_paid = models.BooleanField(default=False)
    date_paid = models.DateField(default=None, blank=True, null=True)
    date_entered = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.service_ticket.customer} - {self.service_ticket}'

    def get_absolute_url(self):
        return reverse('service:invoice_list')


class InvoiceDetail(models.Model):
    invoice = models.ForeignKey(Invoice, related_name='+', on_delete=models.CASCADE)
    part = models.ForeignKey(PartsList, related_name='+', on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    adjusted_cost = models.FloatField(default=0.0)


class Schedule(models.Model):
    service_ticket = models.ForeignKey(ServiceTicket, related_name='+', on_delete=models.CASCADE)
    date_entered = models.DateTimeField(auto_now_add=True)
    date_scheduled = models.DateTimeField(default=None, blank=True, null=True)

service/forms.py
from django import forms
from .models import ServiceTicket, Schedule, PartsList, Invoice, InvoiceDetail
from customers.models import Customer, CustomerSpa


class ServiceFormBlank(forms.ModelForm):

    class Meta:
        model = ServiceTicket
        fields = '__all__'


class ServiceForm(forms.ModelForm):

    class Meta:
        model = ServiceTicket
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        cust = kwargs.pop('id')
        super(ServiceForm, self).__init__(*args, *kwargs)
        self.fields['customer'].queryset = Customer.objects.filter(id=cust)
        self.fields['spa'].queryset = CustomerSpa.objects.filter(customer_id=cust)


class PartForm(forms.ModelForm):

    class Meta:
        model = PartsList
        fields = '__all__'


class InvoiceForm(forms.ModelForm):

    class Meta:
        model = Invoice
        fields = '__all__'


class InvoiceDetailForm(forms.ModelForm):

    class Meta:
        model = InvoiceDetail
        fields = '__all__'

service/views.py
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required

import users.models
from customers.models import *
from .models import *
from .forms import ServiceForm, ServiceFormBlank, PartForm, InvoiceForm, InvoiceDetailForm


class IsStaffMixin(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff

    def handle_no_permission(self):
        return redirect('users:user_login')


class ServiceTicketList(IsStaffMixin, ListView):
    model = ServiceTicket
    template_name = 'service/ticket_list.html'
    context_object_name = 'out'

    def get_queryset(self):
        return ServiceTicket.objects.filter(is_complete=False)

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = 'Open Service Tickets'
        data['out'] = self.get_queryset()
        return data


class ServiceTicketScratch(IsStaffMixin, CreateView):
    model = ServiceTicket
    template_name = 'service/ticket_form.html'
    context_object_name = 'out'
    form_class = ServiceFormBlank

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = 'Create Service Ticket'
        data['out'] = self.context_object_name
        return data


@login_required(login_url='/users')
def create_service_ticket(request, id):
    cust = Customer.objects.get(id=id)
    kwargs = {'id': id}
    if request.method == 'POST':
        form = ServiceForm(request.POST, **kwargs)
        if form.is_valid():
            form.save()
            messages.success(request, 'Service Request Created Successfully')
            return redirect('customers:customer_detail', id)
    context = {'title': 'Create Service Request', 'form': ServiceForm(**kwargs), 'cust': cust}
    return render(request, 'service/ticket_form.html', context)


@login_required(login_url='/users')
def update_service_ticket(request, id, pk):
    ticket = ServiceTicket.objects.get(pk=pk)
    if request.method == 'POST':
        form = ServiceFormBlank(request.POST, instance=ticket)
        if form.is_valid():
            form.save()
            messages.success(request, 'Service Request updated successfully')
            return redirect('service:ticket_list')

    context = {'title': 'Update Service Ticket', 'form': ServiceFormBlank(instance=ticket)}
    return render(request, 'service/ticket_form.html', context)


class ServiceTicketDetail(IsStaffMixin, DetailView):
    model = ServiceTicket
    template_name = 'service/ticket_detail.html'

    def get_queryset(self):
        return ServiceTicket.objects.filter(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = 'Service Detail'
        return data


@login_required(login_url='/users')
def schedule_list(request):
    out = []
    techs = users.models.InternalUser.objects.filter(position='Technician', is_active=True)
    for t in techs:
        obj = ServiceTicket.objects.filter(is_complete=False, technician=t).order_by('-service_date')
        for o in obj:
            out.append(dict(tech=t.first_name, service_date=o.service_date, customer_id=o.customer_id, customer_name=o.customer.customer_name, ticket_id=o.id))
    context = {'title': 'Service Schedule', 'out': out}
    return render(request, 'service/schedule_list.html', context)


class PartListView(IsStaffMixin, ListView):
    model = PartsList
    template_name = 'service/part_list.html'
    context_object_name = 'out'

    def get_queryset(self):
        return PartsList.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = 'Parts List'
        data['out'] = self.get_queryset()
        return data


class PartDetail(IsStaffMixin, DetailView):
    model = PartsList
    template_name = 'service/part_detail.html'

    def get_queryset(self):
        return PartsList.objects.filter(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = 'Part Detail'
        return data


class PartNew(IsStaffMixin, CreateView):
    model = PartsList
    template_name = 'service/part_form.html'
    context_object_name = 'out'
    form_class = PartForm

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = 'Add Part'
        data['out'] = self.context_object_name
        return data


class PartUpdate(IsStaffMixin, UpdateView):
    model = PartsList
    template_name = ''
    context_object_name = 'out'
    form_class = PartForm

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = 'Update Part'
        data['out'] = self.context_object_name
        return data


class InvoiceNew(IsStaffMixin, CreateView):
    model = Invoice
    template_name = 'service/invoice_form.html'
    context_object_name = 'out'
    form_class = InvoiceForm

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = 'Create Invoice'
        data['out'] = self.context_object_name
        return data


class InvoiceList(IsStaffMixin, ListView):
    model = Invoice
    template_name = 'service/invoice_list.html'
    context_object_name = 'out'

    def get_queryset(self):
        if self.kwargs['closed'] and self.kwargs['closed'] == 'closed':
            return Invoice.objects.filter(is_paid=True).order_by('-date_entered')
        else:
            return Invoice.objects.filter(is_paid=False).order_by('-date_entered')

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = 'Open Invoices'
        data['out'] = self.get_queryset()
        return data


class InvoiceDetail(IsStaffMixin, DetailView):
    model = Invoice
    template_name = 'service/invoice_detail.html'

    def get_queryset(self):
        return Invoice.objects.filter(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = 'Invoice Detail'
        return data


class InvoiceUpdate(IsStaffMixin, UpdateView):
    model = Invoice
    template_name = 'service/invoice_form.html'
    context_object_name = 'out'
    form_class = InvoiceForm

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = 'Update Invoice'
        data['out'] = self.context_object_name
        return data

service/templates/service/invoice_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb 'Invoicing' 'service:invoice_list' %}
    {% breadcrumb 'Invoice Detail' 'service:invoice_detail' object.id %}
{% endblock breadcrumbs %}
{% block content %}
    {% load static %}
	<div class="container">
        <div><small class="text-muted">{% render_breadcrumbs %}</small></div>
        <h1>{{ title }}</h1>
        <div class="row">
            <div class="col-sm-12">
                <div class="card bg-dark">

                </div>
            </div>
        </div>
    </div>
{% endblock content %}

service/templates/service/invoice_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Invoicing" "service:invoice_list" %}
    {% breadcrumb 'Invoice Form' 'service:invoice_new' %}
{% endblock breadcrumbs %}
{% block content %}
    {% load static %}
	<div class="container">
        <div><small class="text-muted">{% render_breadcrumbs %}</small></div>
        <h1>{{ title }}</h1>
        <div class="row">
            <div class="col-sm-12">
                <article class="media content-section">
                      <div class="media-body text-light">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <input type="submit" name="submit" value="Submit">
                        </form>
                      </div>
                </article>
            </div>
        </div>
    </div>
{% endblock content %}

service/templates/service/invoice_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Invoicing" "service:invoice_list" %}
{% endblock breadcrumbs %}
{% block content %}
    {% load static %}
	<div class="container">
        <div><small class="text-muted">{% render_breadcrumbs %}</small></div>
        <h1>{{ title }}</h1>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-condensed table-dark">
                    <tr>
                        <th>Invoice Date</th>
                        <th>Customer</th>
                        <th>Actions</th>
                    </tr>
                    {% for o in out %}
                        <tr>
                            <td>{{ o.date_entered }}</td>
                            <td><a href="{% url 'customers:customer_detail' o.service_ticket.customer_id  %}">{{ o.service_ticket.customer }}</a></td>
                            <td>
                                <a href="{% url 'service:invoice_detail' o.id %}"><i class="fa fa-info"></i></a>&nbsp;
                                <a href="{% url 'service:invoice_update' o.id %}"><i class="fa fa-edit"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

service/templates/service/part_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

service/templates/service/part_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Part List" "service:part_list" %}
    {% breadcrumb 'Part Form' 'service:part_new' %}
{% endblock breadcrumbs %}
{% block content %}
    {% load static %}
	<div class="container">
        <div><small class="text-muted">{% render_breadcrumbs %}</small></div>
        <h1>{{ title }}</h1>
        <div class="row">
            <div class="col-sm-12">
                <article class="media content-section">
                      <div class="media-body text-light">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <input type="submit" name="submit" value="Submit">
                        </form>
                      </div>
                </article>
            </div>
        </div>
    </div>
{% endblock content %}

service/templates/service/part_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Service Tickets" "service:ticket_list" %}
{% endblock breadcrumbs %}
{% block content %}
    {% load static %}
	<div class="container">
        <div><small class="text-muted">{% render_breadcrumbs %}</small></div>
        <h1>{{ title }}</h1>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-condensed table-dark">
                    <tr>
                        <th>Part Number</th>
                        <th>Part Name</th>
                        <th>Actions</th>
                    </tr>
                    {% for o in out %}
                        <tr>
                            <td>{{ o.part_number }}</td>
                            <td>{{ o.part_name }}</td>
                            <td>
                                <a href="{% url 'service:part_update' o.id %}" title="Edit part info"><i class="fa fa-edit"></i></a>&nbsp;
                                <a href="{% url 'service:part_detail' o.id %}" title="Part Detail"><i class="fa fa-info"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

service/templates/service/schedule_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Service Tickets" "service:ticket_list" %}
{% endblock breadcrumbs %}
{% block content %}
    {% load static %}
	<div class="container">
        <div><small class="text-muted">{% render_breadcrumbs %}</small></div>
        <h1>{{ title }}</h1>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-condensed table-dark">
                    <tr>
                        <th>Date</th>
                        <th>Technician</th>
                        <th>Customer</th>
                        <th>Actions</th>
                    </tr>
                    {% for o in out %}
                        <tr>
                            <td>{{ o.service_date }}</td>
                            <td>{{ o.tech }}</td>
                            <td><a href="{% url 'customers:customer_detail' o.customer_id %}">{{ o.customer_name }}</a></td>
                            <td>
                                <a href="{% url 'service:ticket_detail' o.customer_id o.ticket_id %}" title="View Details"><i class="fa fa-info"></i></a>&nbsp;
                                <a href="{% url 'service:ticket_update' o.customer_id o.ticket_id %}" title="Edit"><i class="fa fa-edit"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

service/templates/service/ticket_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb 'Service Requests' 'service:ticket_list' %}
    {% breadcrumb 'Request Detail' 'service:ticket_detail' object.id tix.0.id %}
{% endblock breadcrumbs %}
{% block content %}
    {% load static %}
	<div class="container">
        <div><small class="text-muted">{% render_breadcrumbs %}</small></div>
        <h1>{{ title }}</h1>
        <div class="row">
            <div class="col-sm-12">
                <div class="card bg-dark">
                    <div class="card-header">
                        <p><a href="{% url 'customers:customer_detail' object.customer_id %}">{{ object.customer }}</a> | {{ object.service_date }}&nbsp;<a href="{% url 'service:ticket_update' object.customer_id object.id %}"><i class="fa fa-edit"></i></a></p>
                    </div>
                    <div class="card-body">
                        <p><a href="{% url 'customers:spa_detail' object.customer_id object.spa_id %}">{{ object.spa }}</a></p>
                        <p>Subpanel: {{ object.spa.spa_subpanel }}</p>
                        <p>Water System: {{ object.spa.water_system }}</p>
                        <p>Notes: {{ object.spa.spa_note }}</p>
                    </div>
                    <div class="card-body">
                        <p>Issue:<br><em>{{ object.primary_issue }}</em></p>
                    </div>
                    <div class="card-footer">
                        Complete: {{ object.is_complete }} | Date complete: {{ object.date_completed }} | Under Warranty: {{ object.under_warranty }} | Upfront charges: ${{ object.upfront_charges }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

service/templates/service/ticket_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Service Requests" "service:ticket_list" %}
    {% if cust %}
        {% breadcrumb cust.customer_name 'customers:customer_detail' cust.id %}
    {% endif %}
    {% breadcrumb 'Service Ticket Form' 'service:ticket_new' %}
{% endblock breadcrumbs %}
{% block content %}
    {% load static %}
	<div class="container">
        <div><small class="text-muted">{% render_breadcrumbs %}</small></div>
        <h1>{{ title }}</h1>
        <div class="row">
            <div class="col-sm-12">
                <article class="media content-section">
                      <div class="media-body text-light">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <input type="submit" name="submit" value="Submit">
                        </form>
                      </div>
                </article>
            </div>
        </div>
    </div>
{% endblock content %}

service/templates/service/ticket_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Service Requests" "service:ticket_list" %}
{% endblock breadcrumbs %}
{% block content %}
    {% load static %}
	<div class="container">
        <div><small class="text-muted">{% render_breadcrumbs %}</small></div>
        <h1>{{ title }}</h1>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped table-condensed table-dark">
                    <tr>
                        <th>Service Date</th>
                        <th>Assigned Tech</th>
                        <th>Customer</th>
                        <th>Spa Make/Model</th>
                        <th>Primary Issue</th>
                        <th>Actions</th>
                    </tr>
                    {% for o in out %}
                        <tr>
                            <td>{{ o.service_date }}</td>
                            <td>{{ o.technician }}</td>
                            <td><a href="{% url 'customers:customer_detail' o.customer_id %}">{{ o.customer.customer_name }}</a></td>
                            <td><a href="{% url 'customers:spa_detail' o.customer_id o.spa_id %}">{{ o.spa.spa_make }}/{{ o.spa.spa_model }}</a></td>
                            <td><small>{{ o.primary_issue }}</small></td>
                            <td>
                                <a href="{% url 'service:ticket_detail' o.customer_id o.id %}"><i class="fa fa-info"></i></a>&nbsp;
                                <a href="{% url 'service:ticket_update' o.customer_id o.id %}"><i class="fa fa-edit"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

</body>
</html>