DistinctHottubRepairandService/urls.py
from django.urls import path, include

app_name = 'distinct_hottub'

urlpatterns = [
    path('', include('users.urls')),
    path('customers/', include('customers.urls')),
    path('service/', include('service.urls')),
]

customers/urls.py
from django.urls import path
from . import views

app_name = 'customers'

urlpatterns = [
    path('', views.CustomerList.as_view(), name='customer_list'),
    path('new/', views.CustomerCreate.as_view(), name='customer_new'),
    path('<int:pk>/detail/', views.CustomerDetail.as_view(), name='customer_detail'),
    path('<int:pk>/update/', views.CustomerUpdate.as_view(), name='customer_update'),
    path('<int:pk>/spa/', views.create_spa, name='spa_new'),
    path('<int:id>/spa/<int:pk>/update/', views.UpdateSpa.as_view(), name='spa_update'),
    path('<int:id>/spa/<int:pk>/detail/', views.SpaDetail.as_view(), name='spa_detail'),
]

service/urls.py
from django.urls import path
from . import views

app_name = 'service'

urlpatterns = [
    path('', views.ServiceTicketList.as_view(), name='ticket_list'),
    # path('new/', views.ServiceTicketScratch.as_view(), name='ticket_new'),
    path('<int:id>/new/', views.create_service_ticket, name='ticket_new'),
    path('<int:id>/update/<int:pk>/', views.update_service_ticket, name='ticket_update'),
    path('<int:id>/detail/<int:pk>/', views.ServiceTicketDetail.as_view(), name='ticket_detail'),
    path('schedule/', views.schedule_list, name='schedule_list'),
    path('parts/', views.PartListView.as_view(), name='part_list'),
    path('parts/<int:pk>/detail/', views.PartDetail.as_view(), name='part_detail'),
    path('parts', views.PartUpdate.as_view(), name='part_update'),
    path('parts/new/', views.PartNew.as_view(), name='part_new'),
    # path('invoice/', views.InvoiceList.as_view(), name='invoice_list'),
    path('invoice/<str:closed>/', views.InvoiceList.as_view(), name='invoice_list'),
    path('invoice/new/', views.InvoiceNew.as_view(), name='invoice_new'),
    path('invoive/<int:pk>/detail/', views.InvoiceDetail.as_view(), name='invoice_detail'),
    path('invoice/<int:pk>/update/', views.InvoiceUpdate.as_view(), name='invoice_update'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.login_view, name='user_login'),
    path('logout/', views.logout_view, name='user_logout'),
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('new/', views.UserCreate.as_view(), name='user_new'),
    path('<int:pk>/detail/', views.UserDetail.as_view(), name='user_detail'),
    path('<int:pk>/update/', views.UserUpdate.as_view(), name='user_update'),
]

customers/models.py
import datetime
from django.shortcuts import reverse
from django.db import models


class Customer(models.Model):
    customer_name = models.CharField(default=None, max_length=200)
    contact_first = models.CharField(default=None, max_length=100)
    contact_last = models.CharField(default=None, max_length=100, blank=True, null=True)
    contact_phone = models.CharField(default=None, max_length=12)
    contact_email = models.CharField(default=None, blank=True, null=True, max_length=100)
    address1 = models.CharField(default=None, max_length=200)
    address2 = models.CharField(default=None, max_length=200, blank=True, null=True)
    city = models.CharField(default=None, max_length=100)
    state = models.CharField(default='AZ')
    zip_code = models.CharField(default=None, max_length=12)
    intersection_note = models.CharField(default=None, blank=True, max_length=200, null=True)
    customer_since = models.IntegerField(default=datetime.datetime.now().year)
    customer_notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.customer_name

    def get_absolute_url(self):
        return reverse('customers:spa_new', kwargs={'pk': self.id})


class CustomerSpa(models.Model):
    customer = models.ForeignKey(Customer, related_name='+', on_delete=models.CASCADE)
    spa_make = models.CharField(default=None, max_length=200)
    spa_model = models.CharField(default=None, max_length=100)
    spa_subpanel = models.CharField(default=None, max_length=100, blank=True, null=True)
    water_system = models.CharField(default=None, max_length=100, blank=True, null=True)
    serial_number = models.CharField(default=None, max_length=100, blank=True, null=True)
    installed_date = models.DateField(default=None, blank=True, null=True)
    spa_note = models.TextField(default=None, blank=True, null=True)

    def __str__(self):
        return f'{self.spa_make} {self.spa_model} ({self.serial_number})'

    def get_absolute_url(self):
        return reverse('customers:customer_detail', kwargs={'pk': self.customer.id})

customers/forms.py
from django import forms
from .models import Customer, CustomerSpa


class CustomerForm(forms.ModelForm):

    class Meta:
        model = Customer
        fields = '__all__'


class CustomerSpaForm(forms.ModelForm):

    class Meta:
        model = CustomerSpa
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        cust = kwargs.pop('pk')
        super(CustomerSpaForm, self).__init__(*args, **kwargs)
        self.fields['customer'].queryset = Customer.objects.filter(id=cust)
        

customers/views.py
from django.contrib import messages
from django.shortcuts import HttpResponseRedirect, redirect, render, get_object_or_404
from django.views.generic import (ListView, DetailView, CreateView, UpdateView)
from django.contrib.auth.decorators import login_required

import service.models
from service.views import IsStaffMixin
from .models import *
from .forms import *


class CustomerList(IsStaffMixin, ListView):
    model = Customer
    template_name = 'customers/customer_list.html'
    context_object_name = 'out'

    def get_queryset(self):
        return Customer.objects.all().order_by('customer_name')

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super(CustomerList, self).get_context_data(**kwargs)
        data['title'] = 'Customer List'
        data['out'] = self.get_queryset()
        return data


class CustomerCreate(IsStaffMixin, CreateView):
    model = Customer
    template_name = 'customers/customer_form.html'
    form_class = CustomerForm
    context_object_name = 'out'

    def get_context_data(self, **kwargs):
        data = super(CustomerCreate, self).get_context_data(**kwargs)
        data['title'] = 'Add Customer'
        data['out'] = self.context_object_name
        return data


class CustomerDetail(IsStaffMixin, DetailView):
    model = Customer
    template_name = 'customers/customer_detail.html'

    def get_queryset(self):
        return Customer.objects.filter(id=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        spas = CustomerSpa.objects.filter(customer_id=self.kwargs['pk'])
        service_list = service.models.ServiceTicket.objects.filter(customer_id=self.kwargs['pk'])
        data = super(CustomerDetail, self).get_context_data(**kwargs)
        data['title'] = 'Customer Detail'
        data['spas'] = spas
        data['service_tix'] = service_list
        data['out'] = self.get_queryset()
        return data


class CustomerUpdate(IsStaffMixin, UpdateView):
    model = Customer
    template_name = 'customers/customer_form.html'
    form_class = CustomerForm

    def get_success_url(self):
        return reverse('customers:customer_detail', kwargs={'pk': self.kwargs['pk']})


@login_required(login_url='/users')
def create_spa(request, pk):
    obj = Customer.objects.get(pk=pk)
    kwargs = {'pk': pk}
    if request.method == 'POST':
        form = CustomerSpaForm(request.POST or None, **kwargs)
        if form.is_valid():
            form.save()
            messages.success(request, 'Spa created successfully')
            return redirect('customers:customer_detail', pk)
    context = {'title': 'Create new Spa', 'form': CustomerSpaForm(**kwargs), 'object': obj}
    return render(request, 'customers/spa_form.html', context)


class UpdateSpa(IsStaffMixin, UpdateView):
    model = CustomerSpa
    template_name = 'customers/spa_form.html'
    form_class = CustomerSpaForm

    def get_form_kwargs(self):
        kwargs = super(UpdateSpa, self).get_form_kwargs()
        kwargs['pk'] = self.kwargs['pk']
        return kwargs


class SpaDetail(IsStaffMixin, DetailView):
    model = CustomerSpa
    template_name = 'customers/spa_detail.html'

    def get_queryset(self):
        return CustomerSpa.objects.filter(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        tix = service.models.ServiceTicket.objects.filter(spa_id=self.kwargs['pk'])
        data = super().get_context_data(**kwargs)
        data['title'] = 'Spa Detail'
        data['tix'] = tix
        return data

customers/templates/customers/customer_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Customers" "customers:customer_list" %}
    {% breadcrumb object.customer_name 'customers:customer_detail' object.id %}
{% endblock breadcrumbs %}
{% block content %}
    {% load static %}
	<div class="container">
        <div><small class="text-muted">{% render_breadcrumbs %}</small></div>
        <h1>{{ title }}</h1>
        <div class="row">
            <div class="col-sm-12">
                <div class="card bg-dark">
                    <div class="card-header">
                        <p>{{ object.customer_name }}&nbsp;
                            <a href="{% url 'customers:customer_update' object.id %}" title="Edit customer"><i class="fa fa-edit"></i></a>
                            &nbsp;<a href="{% url 'service:ticket_new' object.id %}" title="Create Service Request"><i class="fa fa-plus"></i></a>
                        </p>
                    </div>
                    <div class="card-body">
                        <table class="table table-condensed">
                            <tr>
                                <td>Contact Name:</td>
                                <td>{{ object.contact_first }} {{ object.contact_last }}</td>
                            </tr>
                            <tr>
                                <td>Contact Info: </td>
                                <td>{{ object.contact_phone }}&nbsp;|&nbsp;{{ object.contact_email }}</td>
                            </tr>
                            <tr>
                                <td>Spa Info:<br>({{ spas.count }} spa) <a href="{% url 'customers:spa_new' object.id %}" title="Add spa"><i class="fa fa-plus"></i></a></td>
                                <td>
                                    {% for s in spas %}
                                        <p>
                                            <a href="{% url 'customers:spa_detail' object.id s.id %}">{{ s.spa_make }} {{ s.spa_model }}<br>{{ s.serial_number }}</a><br>
                                            <a href="{% url 'customers:spa_update' object.id s.id %}" title="Edit Spa Info"><i class="fa fa-edit"></i></a>
                                        </p>
                                    {% endfor %}
                                </td>
                            </tr>
                            <tr>
                                <td>Notes:</td>
                                <td>{{ object.customer_notes }}</td>
                            </tr>
                            <tr>
                                <td>Service History:</td>
                                <td>
                                    {% for tix in service_tix %}
                                        <p>Service Date: <a href="{% url 'service:ticket_detail' object.id tix.id %}">{{ tix.service_date }}</a> | Is Complete: {{ tix.is_complete }}</p>
                                    {% endfor %}
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

customers/templates/customers/customer_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Customers" "customers:customer_list" %}
{% endblock breadcrumbs %}
{% block content %}
    {% load static %}
	<div class="container">
        <div><small class="text-muted">{% render_breadcrumbs %}</small></div>
        <h1>{{ title }}</h1>
        <div class="row">
            <div class="col-sm-12">
                <article class="media content-section">
                      <div class="media-body text-light">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <input type="submit" name="submit" value="Submit">
                        </form>
                      </div>
                </article>
            </div>
        </div>
    </div>
{% endblock content %}

customers/templates/customers/customer_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Customers" "customers:customer_list" %}
{% endblock breadcrumbs %}
{% block content %}
    {% load static %}
	<div class="container">
        <div><small class="text-muted">{% render_breadcrumbs %}</small></div>
        <h1>{{ title }}</h1>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped table-condensed table-dark">
                    <tr>
                        <th>Customer Name</th>
                        <th>Address</th>
                        <th>Contact</th>
                        <th>Phone</th>
                        <th>Last Service</th>
                        <th>Actions</th>
                    </tr>
                    {% for o in out %}
                        <tr>
                            <td><a href="{% url 'customers:customer_detail' o.id %}">{{ o.customer_name }}</a></td>
                            <td>{{ o.address1 }} {{ o.city }} {{ o.state }} {{ o.zip_code }}</td>
                            <td>{{ o.contact_first }} {{ o.contact_last }}</td>
                            <td>{{ o.contact_phone }}</td>
                            <td></td>
                            <td>
                                <a href="{% url 'service:ticket_new' o.id %}" title="Create service request"><i class="fa fa-plus"></i></a>&nbsp;
                                <a href="{% url 'customers:customer_update' o.id %}" title="Edit customer info"><i class="fa fa-edit"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

customers/templates/customers/spa_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Customers" "customers:customer_list" %}
    {% breadcrumb object.customer 'customers:customer_detail' object.customer_id %}
    {% breadcrumb 'Spa Detail' 'customers:spa_detail' object.customer_id object.id %}
{% endblock breadcrumbs %}
{% block content %}
    {% load static %}
	<div class="container">
        <div><small class="text-muted">{% render_breadcrumbs %}</small></div>
        <h1>{{ title }}</h1>
        <div class="row">
            <div class="col-sm-12">
                <div class="card bg-dark">
                    <div class="card-header">
                        <p>{{ object.spa_make }}&nbsp;{{ object.spa_model }}&nbsp;<a href="{% url 'customers:spa_update' object.customer_id object.id %}"><i class="fa fa-edit"></i></a></p>
                    </div>
                    <div class="card-body">
                        Serial: {{ object.serial_number }}<br>
                        Subpanel: {{ object.spa_subpanel }}<br>
                        Water System: {{ object.water_system }}<br>
                        Notes: {{ object.spa_note }}
                    </div>
                    <div class="card-footer">
                        {% for t in tix %}
                            <p><a href="{% url 'service:ticket_detail' t.customer_id t.id %}">{{ t.service_date }}</a> - {{ t.primary_issue }}</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

customers/templates/customers/spa_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Customers" "customers:customer_list" %}
    {% breadcrumb object.customer 'customers:customer_detail' object.id %}
    {% breadcrumb 'Customer Spa Form' 'customers:customer_spa' %}
{% endblock breadcrumbs %}
{% block content %}
    {% load static %}
	<div class="container">
        <div><small class="text-muted">{% render_breadcrumbs %}</small></div>
        <h1>{{ title }}</h1>
        <div class="row">
            <div class="col-sm-12">
                <article class="media content-section">
                      <div class="media-body text-light">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <input type="submit" name="submit" value="Submit">
                        </form>
                      </div>
                </article>
            </div>
        </div>
    </div>
{% endblock content %}