DistinctHottubRepairandService/urls.py
from django.urls import path, include

app_name = 'distinct_hottub'

urlpatterns = [
    path('', include('users.urls')),
    path('customers/', include('customers.urls')),
    path('service/', include('service.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.login_view, name='user_login'),
    path('logout/', views.logout_view, name='user_logout'),
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('new/', views.UserCreate.as_view(), name='user_new'),
    path('<int:pk>/detail/', views.UserDetail.as_view(), name='user_detail'),
    path('<int:pk>/update/', views.UserUpdate.as_view(), name='user_update'),
]

users/models.py
from django.shortcuts import reverse
from django.db import models
from django.contrib.auth.models import User


class InternalUser(User):
    position = models.CharField(default=None, blank=True, null=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name} ({self.position})'

    def get_absolute_url(self):
        return reverse('users:user_list')

users/forms.py
from django import forms
from .models import InternalUser


class UserForm(forms.ModelForm):

    class Meta:
        model = InternalUser
        fields = ['first_name', 'last_name', 'username', 'password', 'email', 'is_staff', 'position']

users/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, HttpResponseRedirect, reverse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, UpdateView, ListView, CreateView

from service.views import IsStaffMixin
from .models import InternalUser
from .forms import UserForm


def login_view(request):
    context = {'title': 'Login'}
    if request.method == 'POST':
        username = request.POST['username']
        pw = request.POST['password']
        user = authenticate(request, username=username, password=pw)
        if user is not None:
            login(request, user)
            return redirect('customers:customer_list')
        else:
            messages.info(request, 'Login Failed')
            context['form'] = AuthenticationForm()
    else:
        context['form'] = AuthenticationForm()
    return render(request, 'users/login.html', context)


@login_required(login_url='/users')
def logout_view(request):
    logout(request)
    messages.success(request, 'logout successful')
    return HttpResponseRedirect('/')


class UserListView(IsStaffMixin, ListView):
    model = InternalUser
    template_name = 'users/user_list.html'
    context_object_name = 'out'

    def get_queryset(self):
        return InternalUser.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        data = super().get_context_data(**kwargs)
        data['title'] = 'User List'
        data['my_id'] = self.request.user.id
        data['out'] = self.get_queryset()
        return data


class UserDetail(IsStaffMixin, DetailView):
    model = InternalUser
    template_name = 'users/user_detail.html'

    def get_queryset(self):
        return InternalUser.objects.filter(id=self.kwargs['pk'])


class UserCreate(IsStaffMixin, CreateView):
    model = InternalUser
    template_name = 'users/user_form.html'
    form_class = UserForm

    def get_success_url(self):
        return reverse('users:user_list')

    def form_valid(self, form):
        user = form.save(commit=True)
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        return redirect('users:user_detail', self.kwargs.get('pk'))


class UserUpdate(IsStaffMixin, UpdateView):
    model = InternalUser
    template_name = 'users/user_form.html'
    form_class = UserForm

    def get_success_url(self):
        return reverse('users:user_list')

    def form_valid(self, form):
        user = form.save(commit=True)
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        return redirect('users:user_detail', self.kwargs.get('pk'))

users/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {% load static %}
    <div class="container">
        <h1>{{ title }}</h1>
        <div class="row">
            <div class="col-sm-12">
                <article class="media content-section">
                      <div class="media-body">
                        <form action="." method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <input type="submit" name="submit" value="Submit">
                        </form>
                      </div>
                </article>
            </div>
        </div>
    </div>

{% endblock content %}

users/templates/users/user_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "User List" "users:user_list" %}
    {% breadcrumb "User Update" "users:user_update" object.id %}
    {% breadcrumb object.last_name "users:user_detail" object.id %}
{% endblock breadcrumbs %}
{% block content %}
    {% load static %}
	<div class="container">
        <div><small class="text-muted">{% render_breadcrumbs %}</small></div>
        <h1>{{ title }}</h1>
        <div class="row">
            <div class="col-sm-12">
                <article class="media content-section">
                    <div class="media-body">
                        <div class="article-metadata">
                            <small class="text-muted"><b>Last login: </b>{{ object.last_login }} |
                                <a href="{% url 'users:user_update'  object.id %}"><i class="fa fa-edit"></i></a>
                            </small>
                        </div>
                        <h4>{{ object.first_name }} {{ object.last_name }}</h4>
                        <p class="article-content"><b>Username: </b>{{ object.username }}
                            <b>Position: </b>{{ object.position }}</p>
                    </div>
                </article>
            </div>
        </div>
    </div>

{% endblock content %}

users/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "User List" "users:user_list" %}
    {% breadcrumb 'User Form' "users:user_update" %}
{% endblock breadcrumbs %}
{% block content %}
    {% load static %}
	<div class="container">
        <div><small class="text-muted">{% render_breadcrumbs %}</small></div>
        <h1>{{ title }}</h1>
        <div class="row">
            <div class="col-sm-12">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" name="submit" value="Submit">
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

users/templates/users/user_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "User List" "users:user_list" %}
{% endblock breadcrumbs %}
{% block content %}
    {% load static %}
	<div class="container">
        <div><small class="text-muted">{% render_breadcrumbs %}</small></div>
        <h1>{{ title }}</h1>
        <div class="row">
            <div class="col-sm-12">
                <p><a href="{% url 'users:user_new' %}" title="Create new user"><i class="fa fa-plus"></i></a></p>
                <table class="table table-condensed table-dark">
                    <tr>
                        <td>Name</td>
                        <th>Username</th>
                        <th>Email</th>
                        <th>Position</th>
                        <th>Actions</th>
                    </tr>
                    {% for o in out %}
                        <tr>
                            <td>{{ o.first_name }} {{ o.last_name }}</td>
                            <td>{{ o.username }}</td>
                            <td>{{ o.email }}</td>
                            <td>{{ o.position }}</td>
                            <td>
                                <a href="{% url 'users:user_detail' o.id %}"><i class="fa fa-info"></i></a>&nbsp;
                                {% if o.id == my_id %}
                                    <a href="{% url 'users:user_update' o.id %}"><i class="fa fa-edit"></i></a>
                                {% else %}
                                    -
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/user_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb 'User Form' "users:user_update" %}
{% endblock breadcrumbs %}
{% block content %}
    {% load static %}
	<div class="container">
        <div><small class="text-muted">{% render_breadcrumbs %}</small></div>
        <h1>{{ title }}</h1>
        <div class="row">
            <div class="col-sm-12">
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="submit" name="submit" value="Submit">
                </form>
            </div>
        </div>
    </div>

{% endblock content %}