DistinctHottubRepairandService/urls.py
from django.urls import path, include

app_name = 'distinct_hottub'

urlpatterns = [
    path('', include('users.urls')),
    path('customers/', include('customers.urls')),
    path('service/', include('service.urls')),
]

customers/urls.py
from django.urls import path
from . import views

app_name = 'customers'

urlpatterns = [
    path('', views.CustomerList.as_view(), name='customer_list'),
    path('new/', views.CustomerCreate.as_view(), name='customer_new'),
    path('<int:pk>/detail/', views.CustomerDetail.as_view(), name='customer_detail'),
    path('<int:pk>/update/', views.CustomerUpdate.as_view(), name='customer_update'),
    path('<int:pk>/spa/', views.create_spa, name='spa_new'),
    path('<int:id>/spa/<int:pk>/update/', views.UpdateSpa.as_view(), name='spa_update'),
    path('<int:id>/spa/<int:pk>/detail/', views.SpaDetail.as_view(), name='spa_detail'),
]

service/urls.py
from django.urls import path
from . import views

app_name = 'service'

urlpatterns = [
    path('', views.ServiceTicketList.as_view(), name='ticket_list'),
    # path('new/', views.ServiceTicketScratch.as_view(), name='ticket_new'),
    path('<int:id>/new/', views.create_service_ticket, name='ticket_new'),
    path('<int:id>/update/<int:pk>/', views.update_service_ticket, name='ticket_update'),
    path('<int:id>/detail/<int:pk>/', views.ServiceTicketDetail.as_view(), name='ticket_detail'),
    path('schedule/', views.schedule_list, name='schedule_list'),
    path('parts/', views.PartListView.as_view(), name='part_list'),
    path('parts/<int:pk>/detail/', views.PartDetail.as_view(), name='part_detail'),
    path('parts', views.PartUpdate.as_view(), name='part_update'),
    path('parts/new/', views.PartNew.as_view(), name='part_new'),
    # path('invoice/', views.InvoiceList.as_view(), name='invoice_list'),
    path('invoice/<str:closed>/', views.InvoiceList.as_view(), name='invoice_list'),
    path('invoice/new/', views.InvoiceNew.as_view(), name='invoice_new'),
    path('invoive/<int:pk>/detail/', views.InvoiceDetail.as_view(), name='invoice_detail'),
    path('invoice/<int:pk>/update/', views.InvoiceUpdate.as_view(), name='invoice_update'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.login_view, name='user_login'),
    path('logout/', views.logout_view, name='user_logout'),
    path('users/', views.UserListView.as_view(), name='user_list'),
    path('new/', views.UserCreate.as_view(), name='user_new'),
    path('<int:pk>/detail/', views.UserDetail.as_view(), name='user_detail'),
    path('<int:pk>/update/', views.UserUpdate.as_view(), name='user_update'),
]

templates/base.html
{% load static %}
{% load django_bootstrap_breadcrumbs %}
<!DOCTYPE html>
<html lang="en">
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'main.css' %}">

	{% if title %}
		<title>Distinct Hot Tub Repair and Service: {{ title }}</title>
	{% else %}
		<title>Distinct Hot Tub Repair and Service</title>
	{% endif %}

</head>

<body>
	<header class="site-header">

      <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'service:schedule_list' %}"><img alt="Distinct Hot Tub Repair and Service" src="{% static 'images/letter-logo1_sm.png' %}"></a>
        {% if user.is_authenticated %}
{#            <a class="navbar-brand mr-4" href="{% url 'customers:customer_list' %}">Home</a>#}
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
                <div class="btn-group">
                    <a class="nav-link dropdown-toggle" href="#" id="carddrp" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Customers</a>
                    <div class="dropdown-menu" aria-labelledby="carddrp">
                        <a class="dropdown-item" href="{% url 'customers:customer_list' %}">Customer List</a>
                        <a class="dropdown-item" href="{% url 'customers:customer_new' %}">Add Customer</a>
                    </div>
                </div>
                <div class="btn-group">
                    <a class="nav-link dropdown-toggle" href="#" id="pldrp" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Service/Scheduling</a>
                    <div class="dropdown-menu" aria-labelledby="pldrp">
                        <a class="dropdown-item" href="{% url 'service:schedule_list' %}">View Schedule</a>
                        <a class="dropdown-item" href="{% url 'service:ticket_list' %}">Service Request List</a>
{#                            <a class="dropdown-item" href="{% url 'service:ticket_new' %}">Create New Service Request</a>#}
                    </div>
                </div>
                <div class="btn-group">
                    <a class="nav-link dropdown-toggle" href="#" id="partdrp" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Parts/Inventory</a>
                    <div class="dropdown-menu" aria-labelledby="partdrp">
                        <a class="dropdown-item" href="{% url 'service:part_list' %}">Parts List</a>
                        <a class="dropdown-item" href="{% url 'service:part_new' %}">Add New Part</a>
                    </div>
                </div>
                <div class="btn-group">
                    <a class="nav-link dropdown-toggle" href="#" id="billdrp" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Billing</a>
                    <div class="dropdown-menu" aria-labelledby="billdrp">
                        <a class="dropdown-item" href="{% url 'service:invoice_new' %}">Create Invoice</a>
                        <a class="dropdown-item" href="{% url 'service:invoice_list' 'open' %}">Open Invoices</a>
                        <a class="dropdown-item" href="{% url 'service:invoice_list' 'closed' %}">Closed Invoices</a>

                    </div>
                </div>
            </div>
            <!-- Navbar Right Side -->

            <div class="navbar-nav">
              {% if user.is_authenticated %}
                  <div class="btn-group">
                        <a class="nav-link dropdown-toggle" href="#" id="mgtdrp" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Manage</a>
                        <div class="dropdown-menu" aria-labelledby="mgtdrp">
                            <a class="dropdown-item" href="{% url 'users:user_list' %}">Users</a>
                            <a class="dropdown-item" href="{% url 'users:user_detail' user.id %}">My Profile</a>
                            <a class="dropdown-item" href="{% url 'users:user_logout' %}">Logout</a>
                        </div>
                    </div>
{#                  <a class="nav-item nav-link" href="{% url 'users:user_detail' user.id %}">My Profile</a>#}
{#                  <a class="nav-item nav-link" href="{% url 'users:user_logout' %}">Logout</a>#}
              {% else %}
                <a class="nav-item nav-link" href="{% url 'users:user_login' %}">Login</a>
              {% endif %}
            </div>
          </div>
        {% endif %}
        </div>
      </nav>
    </header>
    <p>&nbsp;</p>
	<main role="main" class="container">

        {% block breadcrumbs %}
            {% clear_breadcrumbs %}
            {% breadcrumb "Home" "/" %}
        {% endblock breadcrumbs %}

      <div class="row">
        <div class="col-md-12">
            <br><br><br>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
            {% endif %}

            {% block content %}
                {% render_breadcrumbs %}
            {% endblock %}
        </div>
      </div>

    </main>
    <div class="container">

        <p>&nbsp;</p>
        <footer class="site-footer">

        <p>
            <small class="text-muted">DC </small>
        </p>
    </footer>
    </div>
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>